### ISSUE TITLE
Add dependencies to setup script and document them

### ISSUE THREAD

**Issue by alimanfoo** [rrlove/compkaryo#2]
The script depends on numpy and scikit-allel. It's a good idea to add dependencies to the setup.py script via an [install_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires) entry, which will mean that these get installed automatically when installing your package via pip. It would probably also be worth noting in the readme that the package depends on numpy and scikit-allel, in case anyone is taking another installation route and wants to install dependencies by hand first.

**Comment by rrlove** [comment]
Done. Thanks Alistair!
